
name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: "npm"
          registry-url: https://npm.pkg.github.com/

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npx snowpack build
